name: nan_banking_app_mai_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  unicons:
  google_fonts:

  #Maps
  # google_maps_flutter:
  # geolocator:
  # geocoding: 
  #
  photo_view: ^0.12.0
  # image_picker:
  # google_fonts:
  flutter_html: ^0.8.2
  html: ^0.13.3
  fluttertoast:

  # intl: ^0.17.0 #For multi language_pickers & date format
  carousel_slider: ^4.0.0
  # logger:
  dio:
  # get_storage:
  # get:
  badges: ^2.0.1
  flutter_rating_bar: ^4.0.0
  # open_file:
  path_provider:
  # awesome_notifications: 
  # unicons: ^2.1.1
  #form
  flutter_form_builder:
  # form_builder_extra_fields: ^7.0.0
  # form_builder_validators:
  # another_flushbar:
  change_app_package_name:
  # sms_autofill:
  # connectivity_plus: ^2.2.0
  # shimmer:
  # pocketbase: ^0.5.0+1
  loading_animation_widget:
  getwidget: ^3.0.1
  flutter_calendar_carousel: ^2.4.1
  table_calendar: ^3.0.8
  flutter_otp_text_field: ^1.1.1
  rive: ^0.10.4
  buttons_tabbar: ^1.3.6 
  url_launcher:
  # universal_html: ^1.2.3
  flutter_screenutil: ^5.5.3+2

  # authentification
  flutter_svg: ^1.0.3
  # animated_splash_screen: ^1.1.0
  # syncfusion_flutter_charts: ^21.2.5

  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.6.0
  date_field: ^3.0.5
  intl: ^0.18.1
  flutter_adaptive_scaffold: ^0.1.3
  adaptive_layout: ^0.1.7
  syncfusion_flutter_datagrid: ^21.2.4
  provider: ^6.0.5
  awesome_snackbar_content: ^0.1.1
  # badges: ^3.1.1
  get_storage: ^2.1.1
  flutter_spinkit: ^5.2.0
  another_flushbar:
  fl_chart: ^0.62.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
    - assets/RiveAssets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

